home/urls.py
from django.urls import path
from .views import about, event_booking, faq, home,contact, contact_success, privacy, refunds, tc, service, work

app_name = "home"

urlpatterns = [
    path('', home, name="index"),
    path('contact/', contact, name="contact"),
    path('contact-success/', contact_success, name="contactsuccess"),
    path('refunds/', refunds, name="refunds"),
    path('privacy/', privacy, name="privacy"),
    path('tc/', tc, name="tc"),
    path('service/', service, name="service"),
    path('about/', about, name="about"),
    path('faq/', faq, name="faq"),
    path('work/', work, name="work"),
    path('event-booking/', event_booking, name="event"),

]

kodecamp_hire/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('accounts/', include("accounts.urls"))

]

home/models.py
from django.db import models

# Create your models here.
class Newsletter(models.Model):
    email = models.EmailField()
    time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email

class Contact(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField()
    phonecode = models.CharField(max_length=7)
    phone = models.CharField(max_length=30)
    message = models.CharField(max_length=1000)
    time = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.message

class Event(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField()
    phone = models.CharField(max_length=20)
    color = models.CharField(max_length=50)
    location = models.CharField(max_length=200)
    date = models.CharField(max_length=50)
    time = models.CharField(max_length=50)
    budget = models.CharField(max_length=50)
    event_type = models.CharField(max_length=100)
    details = models.CharField(max_length=1000)
    time = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.event_type

home/views.py
from django.shortcuts import render, redirect
from .models import Event, Newsletter, Contact
from django.contrib import messages
# Create your views here.
def home(request):
    if request.method == "POST":
        Email = request.POST.get("email")
        if Newsletter.objects.filter(email=Email).exists():
            messages.error(request, "Already a Subscriber")
            return redirect("home:index")
        else:
            Email = request.POST.get("email")
            subscribe = Newsletter(email=Email)
            subscribe.save()
            messages.success(request, "Successfully subscribed")
            return redirect("home:index")

    return render(request, "home/index.html")

def contact(request):
    if request.method == "POST":
        name = request.POST.get("name")
        email = request.POST.get("email")
        phonecode = request.POST.get("phonecode")
        phone = request.POST.get("phone")
        message= request.POST.get("message")
        details = Contact(name = name, email = email, phonecode = phonecode, phone = phone, message = message)
        details.save()

        return redirect("home:contactsuccess")

    return render(request, "home/contact.html")


def event_booking(request):
    if request.method == "POST":
        name = request.POST.get("name")
        email = request.POST.get("email")
        phone = request.POST.get("phone")
        color = request.POST.get("color")
        location = request.POST.get("location")
        date = request.POST.get("date")
        time = request.POST.get("time")
        budget = request.POST.get("budget")
        eventtype = request.POST.get("eventtype")
        details= request.POST.get("details")
        event = Event(name = name, email = email, phone = phone, color=color, location=location, date=date,
        time = time, budget=budget, event_type=eventtype, details = details)
        event.save()

        messages.success(request, "Successfully booked an Event, We'll get in touch with you")
        return redirect("home:event")
    return render(request, "home/event-booking.html")

def contact_success(request):
    return render(request, "home/contact-success.html")

def refunds(request):
    return render(request, "home/refunds.html")

def privacy(request):
    return render(request, "home/privacy.html")

def tc(request):
    return render(request, "home/tc.html")

def service(request):
    return render(request, "home/service.html")

def about(request):
    return render(request, "home/about.html")

def faq(request):
    return render(request, "home/faq.html")

def work(request):
    return render(request, "home/work.html")

home/templates/home/service.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Services | Crystal Events</title>
  <link rel="stylesheet" href="{% static 'home\css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'home\css/service.css' %}">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css" />
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
  <link rel="icon" href="{% static 'home\favicon.ico' %}">
</head>

<body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-light py-lg-3 mt-3" style="border: 2px solid #F5820E;">
      <div class="container">
        <a href="{% url 'home:index' %}" class="navbar-brand">
          <img src="{% static 'home\img/landing-page img/site-logo.png' %}" width="20" height="20" class="img-fluid" alt="logo" />
          <span class="site-logo">CRYSTALEVENT</span>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ms-auto ">
            <li class="nav-item">
              <a class="nav-link fw-bold bg-signup" href="{% url 'home:event' %}">Book An Event</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <nav class="navbar navbar-expand-lg navbar-light bg-color">
      <div class="container">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mx-auto">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'home:index' %}">
                <p class="fw-bold me-5 actived">Home</p>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home:service' %}">
                <p class="fw-bold me-5 ">Services</p>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home:work' %}">
                <p class="fw-bold me-5">Work</p>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home:faq' %}">
                <p class="fw-bold me-5">FAQ</p>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home:contact' %}">
                <p class="fw-bold me-5">Contact Us</p>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </header>
{% block body %}
  <section id="hero-contents" class="pb-5">
    <div>
      <div class="hero-text py-5">
        <h1 class="text-center" style="color: #7B4107;">Creating Memorable Events is our Passion</h1>
        <div class="border-sec mx-auto mt-4">
        </div>
      </div>
      <div class="hero-img">
        <img src="{% static 'home\./img/services-img/services-heroimg.png' %}" alt="cups" class="img-fluid w-100">
      </div>
    </div>
  </section>

  <section id="short-note" class="pb-5" data-aos="fade-up">
    <div>
      <div class="bg-warning py-5">
        <div class="container">
          <h2 class="text-center mb-4" style="color: #7B4107;">A great Event starts with smart planning</h2>
          <p style="color: #311A03;" class="text-start new-family">We understand that each event is unique. At Crystal
            Events, we
            offer a full range of Services uniquely tailored to suitthat special occassion. Our expert assistance offers
            innovative ideas in Event planninng, Catering Services, Event venue decoration, Music, Entertainment and so
            on. With a meticulous eye for details, we transform an ordinary space to a
            beautiful sight to behold. We do our best to give you a special and unforgettable experience.</p>
        </div>
      </div>
    </div>
  </section>

  <section id="services">
    <div class="heading pb-5">
      <h2 class="text-center py-3" style="background-color: #F79736; color: #7B4107;">Services</h2>
    </div>
    <div class="container pb-5">
      <div class="row justify-content-between">
        <div class="col-lg-6 col-md-6" data-aos="flip-left">
          <img src="{% static 'home\./img/services-img/services-img1.png' %}" alt="event planning" class="w-100 img-fluid">
        </div>
        <div class="col-lg-5 col-md-5 new-family smaller-background" data-aos="zoom-in">
          <h3 class="fs-2 pt-lg-5 pt-0 mt-lg-5 mt-3 mb-lg-3 mb-1" style="color: #7B4107;">Event Planing</h3>
          <p style="color:#898989;" class="fs-4 mb-lg-5 mb-3">We plan the best events ranging from:</p>
          <div class="row smaller-text">
            <div class="col-lg-5 col-md-6 col-4 xs-screen1">
              <p style="background-color: rgba(122, 123, 130, 0.1); color: #626262;"
                class="text-center py-1 rounded-pill">
                Corporate Events</p>
            </div>
            <div class="col-lg-5 col-md-6 col-4 xs-screen1">
              <p style="background-color: rgba(122, 123, 130, 0.1); color: #626262;"
                class="text-center py-1 rounded-pill">Product
                Launch</p>
            </div>
            <div class="col-lg-5 col-md-6 col-4 xs-screen1">
              <p style="background-color: rgba(122, 123, 130, 0.1); color: #626262;"
                class="text-center py-1 rounded-pill">Private Launch </p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="container pb-5">
      <div class="row justify-content-between">
        <div class="col-lg-6 col-md-6" data-aos="flip-left">
          <img src="{% static 'home\./img/services-img/services-img2.png' %}" alt="event planning" class="w-100 img-fluid">
        </div>
        <div class="col-lg-5 col-md-5 new-family smaller-background" data-aos="zoom-in">
          <h3 class="fs-2 pt-lg-5 pt-0 mt-lg-5 mt-3 mb-lg-3 mb-1" style="color: #7B4107;">Event Vendors</h3>
          <p style="color:#898989;" class="new-family fs-3 mb-lg-5 mb-3">Our vendor services cut across</p>
          <div class="row smaller-text">
            <div class="col-lg-4 col-md-5 col-4 xs-screen1">
              <p style="background-color: rgba(122, 123, 130, 0.1); color: #626262;"
                class="text-center py-1 rounded-pill">
                Photography</p>
            </div>
            <div class="col-lg-5 col-md-7 col-5 xs-screen1">
              <p style="background-color: rgba(122, 123, 130, 0.1); color: #626262;"
                class="text-center py-1 rounded-pill">Events decoration</p>
            </div>
            <div class="col-lg-4 col-md-4 col-3 xs-screen1">
              <p style="background-color: rgba(122, 123, 130, 0.1); color: #626262;"
                class="text-center py-1 rounded-pill">Live band</p>
            </div>
            <div class="col-lg-5 col-md-4 col-3 xs-screen1">
              <p style="background-color: rgba(122, 123, 130, 0.1); color: #626262;"
                class="text-center py-1 rounded-pill">Catering</p>
            </div>
            <div class="col-lg-4 col-md-4 col-3 xs-screen1">
              <p style="background-color: rgba(122, 123, 130, 0.1); color: #626262;"
                class="text-center py-1 rounded-pill">
                DJ & MC</p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="container pb-5">
      <div class="row justify-content-between">
        <div class="col-lg-6 col-md-6" data-aos="flip-left">
          <img src="{% static 'home\./img/services-img/services-img3.png' %}" alt="event planning" class="w-100 img-fluid">
        </div>
        <div class="col-lg-5 col-md-5 new-family smaller-background" data-aos="zoom-in">
          <h3 class="fs-2 pt-lg-5 pt-0 mt-lg-5 mt-3 mb-lg-3 mb-1" style="color: #7B4107;">Special Events</h3>
          <p style="color:#898989;" class="new-family fs-3 mb-lg-5 mb-3">We offer you varierties of special events
            ranging from:
          </p>
          <div class="row smaller-text">
            <div class="col-lg-6 col-md-6 col-6 xs-screen1">
              <p style="background-color: rgba(122, 123, 130, 0.1); color: #626262;"
                class="text-center py-1 rounded-pill">
                Engagement parties</p>
            </div>
            <div class="col-lg-6 col-md-6 col-6 xs-screen1">
              <p style="background-color: rgba(122, 123, 130, 0.1); color: #626262;"
                class="text-center py-1 rounded-pill">Child
                Christening</p>
            </div>
            <div class="col-lg-6 col-md-6 col-6 xs-screen1">
              <p style="background-color: rgba(122, 123, 130, 0.1); color: #626262;"
                class="text-center py-1 rounded-pill">
                Surprise Parties</p>
            </div>
            <div class="col-lg-5 col-md-6 col-6 xs-screen1">
              <p style="background-color: rgba(122, 123, 130, 0.1); color: #626262;"
                class="text-center py-1 rounded-pill">
                Bridal Showers</p>
            </div>
            <div class="col-lg-5 col-md-6 col-6 xs-screen1">
              <p style="background-color: rgba(122, 123, 130, 0.1); color: #626262;"
                class="text-center py-1 rounded-pill">
                Baby Showers</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock body %}
<footer id="sec-five" class="pt-5">
  <div class="container">
    <div class="container">
      <div class="row">
        <div class="col-lg-7 mx-auto">
          <form method="post">
            {% csrf_token %}
            <div class="input-group my-3 d-flex flex-wrap gap-3 align-items-center justify-content-center">
              <input type="email" name="email" id="email" class="form-control py-3 d-inline-flex new-family"
                style="background-color: #3A3A3A; color: #ffffff;" placeholder="Email Address"
                aria-label="Email Address" aria-describedby="button-addon2">
              <button class="btn bg-hire text-white btn-lg new-family" type="submit"
                id="button-addon2">SUBSCRIBE</button>
            </div>
          </form>
        </div>
      </div>
    </div>

    <section class="">
      <div class="container text-white mt-3 footer-links">
        <div class="row mt-3 text-start">
          <div class="col-lg-3 col-md-6 col-6 mb-3 new-family">
            <p class="fw-bold mb-3 new-family">COMPANY</p>
            <a href="account.html" class="text-secondary text-decoration-none mb-4 d-block new-family">My Account</a>
            <a href="{% url 'home:about' %}" class="text-secondary text-decoration-none mb-4 d-block new-family">About Us</a>
            <a href="{% url 'home:faq' %}" class="text-secondary text-decoration-none mb-4 d-block new-family">Faqs</a>
            <a href="{% url 'home:contact' %}" class="text-secondary text-decoration-none mb-4 d-block new-family ">Contact Us</a>
          </div>

          <div class="col-lg-3 col-md-6 col-6 mb-3 new-family">
            <p class="fw-bold mb-3 new-family">CUSTOMER SERVICE</p>
            <a href="{% url 'home:tc' %}" class="text-secondary text-decoration-none mb-4 d-block new-family">Terms &
              Conditions</a>
            <a href="{% url 'home:refunds' %}" class="text-secondary text-decoration-none mb-4 d-block new-family">Returns &
              Refunds</a>
            <a href="help-support.html" class="text-secondary text-decoration-none mb-4 d-block new-family">Help &
              Supports</a>
            <a href="{% url 'home:privacy' %}" class="text-secondary text-decoration-none mb-4 d-block new-family">Privacy</a>
          </div>

          <div class="col-lg-3 col-md-6 col-6 mb-3 new-family">
            <p class="fw-bold mb-3 new-family">SOCIAL MEIDA</p>
            <a href="https://twitter.com/"
              class="text-secondary text-decoration-none mb-4 d-block new-family">Twitter</a>
            <a href="https://www.linkedin.com/"
              class="text-secondary text-decoration-none mb-4 d-block new-family">LinkedIn</a>
            <a href="https://instagram.com/"
              class="text-secondary text-decoration-none mb-4 d-block new-family">Instagram</a>
          </div>

          <div class="col-lg-3 col-md-6 col-6 mb-3">
            <p class="fw-bold mb-3 new-family">ARCHIVE</p>
            <a href="pricelist.html" class="text-secondary text-decoration-none mb-4 d-block new-family">Price
              List</a>
            <a href="our-vendor.html" class="text-secondary text-decoration-none mb-4 d-block new-family">Our
              Vendors</a>
            <a href="event-category.html" class="text-secondary text-decoration-none mb-4 d-block new-family">Event
              Category</a>
          </div>

        </div>
      </div>
    </section>
</footer>

  <section id="sec-six" style="background-color: #626262;">
    <div class="text-center text-light p-3">© Crystal events 2022 all rights reserved.</div>
  </section>

  <script src="js/bootstrap.min.js"></script>
  <script src="js/app.js"></script>
  <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
  <script>
    AOS.init({
      duration: 1500,
      once: true,
    });
  </script>
</body>

</html>

home/templates/home/work.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Services | Crystal Events</title>
  <link rel="stylesheet" href="{% static 'home/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'home/css/work.css' %}">
  <link rel="icon" href="favicon.ico">
</head>

<body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-light py-lg-3 mt-3" style="border: 2px solid #F5820E;">
      <div class="container">
        <a href="{% url 'home:index' %}" class="navbar-brand">
          <img src="{% static 'home\img/landing-page img/site-logo.png' %}" width="20" height="20" class="img-fluid" alt="logo" />
          <span class="site-logo">CRYSTALEVENT</span>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ms-auto ">
            <li class="nav-item">
              <a class="nav-link fw-bold bg-signup" href="{% url 'home:event' %}">Book An Event</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <nav class="navbar navbar-expand-lg navbar-light bg-color">
      <div class="container">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mx-auto">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'home:index' %}">
                <p class="fw-bold me-5 actived">Home</p>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home:service' %}">
                <p class="fw-bold me-5 ">Services</p>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home:work' %}">
                <p class="fw-bold me-5">Work</p>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home:faq' %}">
                <p class="fw-bold me-5">FAQ</p>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home:contact' %}">
                <p class="fw-bold me-5">Contact Us</p>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </header>


  <main id="">

    <div class="container d-flex align-items-center justify-content-center my-5">
      <h3 class="display-5 fw-bold text-dark">
        Our featured works
      </h3>
    </div>

    <!-- video section start -->
    <div class="row row-cols-1 row-cols-md-2 g-4 mx-auto" style="width: 95%;">
      <div class="col">
        <div class="">

          <div class="ratio ratio-16x9 embed-responsive ">
            <iframe width="560" height="315" src="https://www.youtube.com/embed/B9UpHVRb8eE"
              title="YouTube video player" frameborder="0"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
              allowfullscreen></iframe>
          </div>

          <div class="card-body">
            <p class="card-text text-center">Exclusive wedding party at <br /> songotedo Lagos.</p>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="">

          <div class="ratio ratio-16x9 embed-responsive ">
            <iframe width="560" height="315" src="https://www.youtube.com/embed/9q4y0FG_DiY"
              title="YouTube video player" frameborder="0"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
              allowfullscreen></iframe>
          </div>

          <div class="card-body">
            <p class="card-text text-center">Exclusive wedding party at <br /> songotedo Lagos.</p>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="">

          <div class="ratio ratio-16x9 embed-responsive ">
            <iframe width="560" height="315" src="https://www.youtube.com/embed/vsx52HqRQYI"
              title="YouTube video player" frameborder="0"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
              allowfullscreen></iframe>
          </div>

          <div class="card-body">
            <p class="card-text text-center">Exclusive wedding party at <br /> songotedo Lagos.</p>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="">

          <div class="ratio ratio-16x9 embed-responsive ">
            <iframe width="560" height="315" src="https://www.youtube.com/embed/zZShwh1_vzk"
              title="YouTube video player" frameborder="0"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
              allowfullscreen></iframe>
          </div>

          <div class="card-body">
            <p class="card-text text-center">Exclusive wedding party at <br /> songotedo Lagos.</p>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="">

          <div class="ratio ratio-16x9 embed-responsive ">
            <iframe width="560" height="315" src="https://www.youtube.com/embed/ddSbxSJHQg0"
              title="YouTube video player" frameborder="0"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
              allowfullscreen></iframe>
          </div>

          <div class="card-body">
            <p class="card-text text-center">Exclusive wedding party at <br /> songotedo Lagos.</p>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="">

          <div class="ratio ratio-16x9 embed-responsive ">
            <iframe width="560" height="315" src="https://www.youtube.com/embed/jLniBUVNC84"
              title="YouTube video player" frameborder="0"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
              allowfullscreen></iframe>
          </div>

          <div class="card-body">
            <p class="card-text text-center">Exclusive wedding party at <br /> songotedo Lagos.</p>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="">

          <div class="ratio ratio-16x9 embed-responsive ">
            <iframe width="560" height="315" src="https://www.youtube.com/embed/lLJ6bFVdBLk"
              title="YouTube video player" frameborder="0"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
              allowfullscreen></iframe>
          </div>

          <div class="card-body">
            <p class="card-text text-center">Exclusive wedding party at <br /> songotedo Lagos.</p>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="">

          <div class="ratio ratio-16x9 embed-responsive ">
            <iframe width="560" height="315" src="https://www.youtube.com/embed/nYmdhXHHe50"
              title="YouTube video player" frameborder="0"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
              allowfullscreen></iframe>
          </div>

          <div class="card-body">
            <p class="card-text text-center">Exclusive wedding party at <br /> songotedo Lagos.</p>
          </div>
        </div>
      </div>
    </div>
    <!-- video section end -->


    <div class="container d-flex align-items-center justify-content-center my-5">
      <a href="https://www.youtube.com/channel/UC1yZ4D3mKu3qtOmDIXrzFkg"><button class="btn bg-hire text-white btn-lg"
          type="button" id="button-addon2">View More Gallery</button></a>
    </div>
  </main>



  <footer id="sec-five" class="pt-5">
    <div class="container">
      <div class="container">
        <div class="row">
          <div class="col-lg-7 mx-auto">
            <div class="input-group my-3 d-flex flex-wrap gap-3 align-items-center justify-content-center">
              <input type="email" class="form-control py-3 d-inline-flex new-family"
                style="background-color: #3A3A3A; color: #ffffff;" placeholder="Email Address"
                aria-label="Email Address" aria-describedby="button-addon2">
              <button class="btn bg-hire text-white btn-lg new-family" type="button"
                id="button-addon2">SUBSCRIBE</button>
            </div>
          </div>
        </div>
      </div>

      <section class="">
        <div class="container text-white mt-3 footer-links">
          <div class="row mt-3 text-start">
            <div class="col-lg-3 col-md-6 col-6 mb-3 new-family">
              <p class="fw-bold mb-3 new-family">COMPANY</p>
              <a href="#" class="text-secondary text-decoration-none mb-4 d-block new-family">My Account</a>
              <a href="{% url 'home:about' %}" class="text-secondary text-decoration-none mb-4 d-block new-family">About Us</a>
              <a href="{% url 'home:faq' %}" class="text-secondary text-decoration-none mb-4 d-block new-family">Faqs</a>
              <a href="{% url 'home:contact' %}" class="text-secondary text-decoration-none mb-4 d-block new-family ">Contact Us</a>
            </div>

            <div class="col-lg-3 col-md-6 col-6 mb-3 new-family">
              <p class="fw-bold mb-3 new-family">CUSTOMER SERVICE</p>
              <a href="{% url 'home:tc' %}" class="text-secondary text-decoration-none mb-4 d-block new-family">Terms &
                Conditions</a>
              <a href="{% url 'home:refunds' %}" class="text-secondary text-decoration-none mb-4 d-block new-family">Returns &
                Refunds</a>
              <a href="#" class="text-secondary text-decoration-none mb-4 d-block new-family">Help &
                Supports</a>
              <a href="{% url 'home:privacy' %}" class="text-secondary text-decoration-none mb-4 d-block new-family">Privacy</a>
            </div>

            <div class="col-lg-3 col-md-6 col-6 mb-3 new-family">
              <p class="fw-bold mb-3 new-family">SOCIAL MEIDA</p>
              <a href="https://twitter.com/"
                class="text-secondary text-decoration-none mb-4 d-block new-family">Twitter</a>
              <a href="https://www.linkedin.com/"
                class="text-secondary text-decoration-none mb-4 d-block new-family">LinkedIn</a>
              <a href="https://instagram.com/"
                class="text-secondary text-decoration-none mb-4 d-block new-family">Instagram</a>
            </div>

            <div class="col-lg-3 col-md-6 col-6 mb-3">
              <p class="fw-bold mb-3 new-family">ARCHIVE</p>
              <a href="#" class="text-secondary text-decoration-none mb-4 d-block new-family">Price
                List</a>
              <a href="#" class="text-secondary text-decoration-none mb-4 d-block new-family">Our
                Vendors</a>
              <a href="#" class="text-secondary text-decoration-none mb-4 d-block new-family">Event
                Category</a>
            </div>

          </div>
        </div>
      </section>
  </footer>

  <section id="sec-six">
    <div class="text-center text-light p-3">© Crystal events 2022 all rights reserved.</div>
  </section>

  <script src="{% static 'home\js/bootstrap.min.js' %}"></script>
</body>

</html>