accounts/urls.py
from django.urls import path
from .views import booking, reset_password, new_password, vendor #account views
from django.contrib.auth import views as auth_views
from django.conf import settings
from . import views
from django.conf.urls.static import static

app_name = "accounts"

urlpatterns = [
    
    path('reset-password/', reset_password, name="reset-password"),
    path('new-password', new_password, name="new-password"),
    path('sign-up', views.signup,name='sign-up'),
    path('signup-done',views.signupDone,name='signup-done'),
    path('login/', views.signin, name="login"),
    path('vendor', vendor, name="vendor"),
    #path('verify', verify, name="verify"),
    path('booking', booking, name="booking"),
    #path('signout/', views.signout, name="signout"),
    path('signout/', auth_views.LogoutView.as_view(template_name ='accounts/signout.html'), name="signout"),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import about, event_booking, faq, home,contact, contact_success, privacy, refunds, tc, service, work

app_name = "home"

urlpatterns = [
    path('', home, name="index"),
    path('contact/', contact, name="contact"),
    path('contact-success/', contact_success, name="contactsuccess"),
    path('refunds/', refunds, name="refunds"),
    path('privacy/', privacy, name="privacy"),
    path('tc/', tc, name="tc"),
    path('service/', service, name="service"),
    path('about/', about, name="about"),
    path('faq/', faq, name="faq"),
    path('work/', work, name="work"),
    path('event-booking/', event_booking, name="event"),

]

kodecamp_hire/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('accounts/', include("accounts.urls"))

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class User_Number(models.Model):
    
    number = models.CharField(max_length=30)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    terms = models.CharField(max_length=10)
    
    def __str__(self):
        return self.user.first_name + ' ' + 'phone number'

class Vendor(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE, default=1)
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phonecode = models.CharField(max_length=5)
    phone = models.CharField(max_length=30)
    categories = models.CharField(max_length=50)
    address = models.CharField(max_length=1000)
    statec= models.CharField(max_length=50)
    lga = models.CharField(max_length=50)
    experience = models.CharField(max_length=1000)
    time = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.name

accounts/views.py
import email
from django.shortcuts import redirect, render
from django.contrib.auth.models import User
from accounts.models import User_Number, Vendor
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth import authenticate, login


# Create your views here.

def reset_password(request):
	if request.method == "POST":
		Email = request.POST.get("email")
		if User.objects.filter(email=Email).exists():
			return redirect("accounts:new-password")
		else:
			messages.error(request, message="User does not exist")
			return redirect("accounts:reset-password")

	return render(request, "accounts/reset-password.html")

def new_password(request):
	if request.method == "POST":
		Email = request.POST.get("email")
		Password1 = request.POST.get("password1")
		Password2 = request.POST.get("password2")
		if User.objects.filter(email=Email).exists() and Password1==Password2:
			user = User.objects.get(email=Email)
			user.set_password(Password2)
			user.save()
            
			return redirect("accounts:login")
		else:
            
			return redirect("accounts:new-password")
			
	return render(request, "accounts/new-password.html")


# Create your views here.

def signup(request):
    if request.method == 'POST':
        firstname = request.POST.get('fname')
        lastname = request.POST.get('lname')
        email = request.POST.get('email')
        phonenumber = request.POST.get('phoneNumber')
        password1 = request.POST.get('password1')
        check = request.POST.get('check1')
        password2 = request.POST.get('password2')
        #checking if user already exists 
        if User.objects.filter(username=email).exists():
            messages.success(request,"User Already Exists :)")
            return render(request, 'accounts/success-sign-up.html')
        else:
            if password2 == password1:
                new_user = User.objects.create_user(username=email,email=email,password=password2,
                                                    first_name=firstname,last_name=lastname)
                user_phone = User_Number(number=phonenumber,user=new_user,terms=check)
                user_phone.save()
                new_user.save()
                messages.success(request,f'Account created for {firstname}')
                return render(request, 'accounts/success-sign-up.html')
    else:
        return render(request, "accounts/sign-up.html")


def signupDone(request):
    return render(request, 'accounts/success-sign-up.html')

def signin(request):
    
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username,password=password)
        if User.objects.filter(username=username).exists():
            messages.success(request,"User Matched:)")
        else:
            messages.error(request, "Email Address not Found")
            return redirect('accounts:login')
        user = authenticate(username=username,password=password)    
        if user is not None:
            login(request, user)
            return redirect('home:index')
        else:
            messages.error(request, "username or password incorrect")
            return redirect('accounts:sign-up')
        
        
    return render(request, "accounts/login.html")

def vendor(request):
    if request.method == "POST":
        #user=request.POST.get("user")
        vendor_name = request.POST.get("name")
        vendor_email = request.POST.get("email")
        vendor_phonecode = request.POST.get("phonecode")
        vendor_phone = request.POST.get("phone")
        vendor_category = request.POST.get("categories")
        vendor_address = request.POST.get("address")
        vendor_state = request.POST.get("state")
        vendor_lga = request.POST.get("lga")
        vendor_experience = request.POST.get("experience")
        if Vendor.objects.filter(email=vendor_email).exists():
            messages.error(request, "Already Had An Appointment With Us")
            return redirect('accounts:vendor')
        else :
            new_vendor = Vendor( name=vendor_name, email=vendor_email, phonecode=vendor_phonecode, phone=vendor_phone, 
                categories=vendor_category, address=vendor_address, statec=vendor_state, lga=vendor_lga, experience=vendor_experience)
            new_vendor.save()      
            verified = Vendor.objects.get(email= vendor_email)
            context = {

                "verified" : verified
            }
        return render(request, "accounts/verify.html", context)
        
    return render(request, "accounts/vendor.html")


def booking(request):
    return render(request, 'accounts/booking.html')

accounts/templates/accounts/booking.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'accounts\css/booking.css' %}" />
  <link rel="stylesheet" href="{% static 'accounts\css/bootstrap.min.css' %}" />
  <link rel="icon" href="{% static 'accounts\favicon.ico' %}">
  <title>Bookings | CRYSTALEVENT</title>
</head>
<body>

  <header>
    <nav class="navbar navbar-expand-lg navbar-light">
      <div class="container-fluid">
        <a href="{% url 'home:index' %}" class="navbar-brand ms-auto">
          <img
            src="{% static 'accounts\./img/landing-page img/site-logo.png' %}"
            width="20"
            height="20"
            class="img-fluid"
            alt="logo"
          />
          <span class="site-logo">CRYSTALEVENT</span>
        </a>
    </nav>
  </header>

  <section id="sect-one">
    <div class="container text-center">
      <img src="{% static 'accounts\./img/landing-page img/success.png' %}" class="img-fluid w-50" alt="success">
      <h3 class="display-5 fw-bold text-center">Appointment booked <br> Succesfully</h3>
      <p class="lead family-one">Kindly be availiable for a meeting on the 27th or 28th of <br> oct 2022 for a live interview with the managment of <br> Crystal events 
      </p>
      <a href="{% url 'home:index' %}">
        <button class="btn text-white btn-lg mb-5 mt-2  bg-hire" type="button" id="button-addon2">Proceed to Home</button>
      </a>
    </div>
  </section>
</body>
</html>

accounts/templates/accounts/check-mail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="css\check-mail.css" />
    <link rel="stylesheet" href="css\bootstrap.min.css" />
    <title> Reset link | CRYSTALEVENT</title>
  </head>
  <body class="position-relative">

    <div class="header-postion w-100 ">
     <div class="d-flex justify-content-between align-content-center w-100">
      <div class="back-button">
        <a href="sign-up.html">
      <button type="submit" class="btn btn-primary border-0 ms-3">Back</button>
        </a>
    </div>
      <!-- <div class="container-fluid"> -->
        <!-- <div class=" d-flex  align-items-end justify-content-end"> -->
          <a class="navbar-brand ms-auto">
            <img
              src="img\landing-page img\site-logo.png"
              width="20"
              height="20"
              class="img-fluid"
              alt="logo"
            />
            <span class="site-logo text-dark">CRYSTALEVENT</span>
          </a>
        <!-- </div> -->
       </div> 
    </div>
    </div>
<!-- <div class="big-screen"> -->
  <div class="container-mobile">
    <section class="d-flex">
      
      <section class="Image">
      </section>
      
      <section class="form   mt-5 ps-md-3 px-lg-5 mt-5 text-center">
        <div class="container container-md">
         <img src="img\check-mail\mail.png" alt="mail" class="img-fluid" style="width: 16rem;">
         <p class="font-playfair fw-bolder fs-1">Check your mail</p>
         <p class="font-source fw-bold">We have sent password recover 
            instructions to your email.</p>
                  
           
            
              <div class=" d-flex justify-content-center mt-4 mb-4">
              <button type="submit" class="btn btn-primary border-0 font-source fw-bold w-auto w-25"> <a href="mailto:gmail.com" class="text-decoration-none text-white">Open email app </a></button>
              </div>
            </form>
        <p class="text-center mt-2 font-source fw-bold">Skip, I’ll confirm later</p>
      </div>
      
      </section>
    </div>
    </section> 
    </div>  
  </body>
</html>

accounts/templates/accounts/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'home/css/login.css' %}" />
    <link rel="stylesheet" href="{% static 'home/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <title>Login | CRYSTALEVENT</title>
  </head>
  <body class="position-relative">

    <div class="header-postion w-100 ">
     <div class="d-flex justify-content-between align-content-center w-100">
      <div class="back-button">
        <a href="{% url 'home:index' %}">
      <button type="submit" class="btn btn-primary border-0 ms-3">Back</button>
        </a>
    </div>
      <!-- <div class="container-fluid"> -->
        <!-- <div class=" d-flex  align-items-end justify-content-end"> -->
          <a href="{% url 'home:index' %}" class="navbar-brand ms-auto">
            <img
              src="{% static 'home/img/landing-page img/site-logo.png' %}"
              width="20"
              height="20"
              class="img-fluid"
              alt="logo"
            />
            <span class="site-logo text-dark">CRYSTALEVENT</span>
          </a>
        <!-- </div> -->
       </div> 
    </div>
    </div>
<!-- <div class="big-screen"> -->
  <div class="container-mobile">
    <section class="d-flex">
      
      <section class="Image">
      </section>
      
      <section class="form   mt-5 ps-md-3 px-lg-5 mt-5">
        <div class="container container-md">
                  
            <h2 class="text-center mt-5 text-log font-playfair" > <span class="ms-2">Log </span> <span class="orange">In</span></h2>

            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            <strong> Message:</strong> {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="close">
            <span aria-hidden="true">&times;</span>
            </button>
            </div>
            {% endfor %}

            <form action="" method="post">
              {% csrf_token %}
              <div class="mb-5">
                <label for="exampleInputEmail1" class="form-label fw-bolder fs-5 label-size font-playfair">Email</label>
                <input type="email" name ="username" class="form-control new-family" placeholder="mariamevents247@gmail.com"    id="exampleInputEmail1" aria-describedby="emailHelp" required>

              <div class="mt-4 ">
                <label for="exampleInputPassword1" class="form-label fw-bolder fs-5 label-size font-playfair">Password</label>
                <div class="input-container">
                <input type="password" name ="password" class="form-control input-field new-family" placeholder="******** " id="exampleInputPassword1" required> 
                <i class="bi bi-eye-slash-fill" id="togglePassword" style="margin-left: -30px; margin-top: 11px;cursor: pointer;"></i>
                </div>
                </div>
                <div class=" d-flex justify-content-end">
                  <p class="
                  orange font-source  fw-bold"> <a href="{% url 'accounts:reset-password' %}" style="text-decoration: none;"> <span class="orange">Forgot Password?</span></p></a> 
                  </div>
              <div class=" d-flex justify-content-center mt-4 mb-4">
              <button type="submit" class="btn btn-primary w-75 border-0 font-source fw-bold new-family">Login</button>
              </div>
            </form>
        <p class="text-center mt-2 font-source fw-bold">Don’t have an account? <a href="{% url 'accounts:sign-up' %}" style="text-decoration: none;"><span class="orange">Create Account</span></a></p>
      </div>
      
      </section>
    </div>
    </section> 
    </div> 
    <script src="{% static 'home/js/script.js' %}"></script> 
  </body>
</html>

accounts/templates/accounts/new-password.html
{% extends "accounts/reset-password.html"%}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css\new-password.css" />
    <link rel="stylesheet" href="css\bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">

    <title>Create new password | CRYSTALEVENT</title>
</head>
{% block body %}
<body>
  <title>Login | CRYSTALEVENT</title>
</head>
<body class="position-relative">

  <div class="header-postion w-100 ">
   <div class="d-flex justify-content-between align-content-center w-100">
    <div class="back-button">
      <a href="{% url 'accounts:reset-password' %}">
    <button type="submit" class="btn btn-primary border-0 ms-3">Back</button>
      </a>
    </div>
        <a  href="" class="navbar-brand ms-auto">
          <img
            src="{% static 'accounts\img\landing-page img\site-logo.png' %}"
            width="20"
            height="20"
            class="img-fluid"
            alt="logo"
          />
          <span class="site-logo text-dark">CRYSTALEVENT</span>
        </a>
      <!-- </div> -->
     </div> 
  </div>
  </div>
<!-- <div class="big-screen"> -->
<div class="container-mobile">
  <section class="d-flex">
    
    <section class="Image">
    </section>
    
    <section class="form   mt-5 ps-md-3 px-lg-5 mt-5">
      <div class="container container-md">
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        <strong> Message:</strong> {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="close">
        <span aria-hidden="true">&times;</span>
        </button>
        </div>
        {% endfor %}
                
          <h2 class="text-center mt-5 text-log font-playfair" > <span class="ms-2">Create  </span> <span class="orange">new password</span></h2>
           <p class="font-source  fw-bold  mt-4 text-center text-log ">Your new password must be different from previous passwords.</p> 
           <form action="" method="post">
            {% csrf_token %}
            <div class="mb-5">
             <label for="exampleInputEmail1" class="form-label fw-bolder fs-5 label-size font-playfair">Email</label>
             <input type="email" class="form-control" placeholder="mariamevents247@gmail.com" name="email" id="email" aria-describedby="emailHelp">
             </div>
            <div class="mt-4 ">
             <label for="exampleInputPassword1" class="form-label fw-bolder fs-5 label-size font-playfair">Password</label>
             <div class="input-container">
             <input type="password" class="form-control input-field  font-source fw-bold" placeholder="******** " name = "password1" id="password1"> 
             <i class="bi bi-eye-slash-fill" id="togglePassword" style="margin-left: -30px; margin-top: 11px;cursor: pointer;"></i>
             </div>
             </div>
             <div class="mt-4 ">
               <label for="exampleInputPassword2" class="form-label fw-bolder fs-5 label-size font-playfair">Confirm Password</label>
               <div class="input-container">
               <input type="password" class="form-control input-field  font-source" placeholder="******** " name = "password2"id="password2"> 
               <i class="bi bi-eye-slash-fill" id="togglePassword" style="margin-left: -30px; margin-top: 11px;cursor: pointer;"></i>
               </div>
               </div>  
               <div class=" d-flex justify-content-center mt-4 mb-4">
                 <button type="submit" class="btn btn-primary w-75 border-0 font-source fw-bold">Reset password</button>
                 </div>
               </form>   
    </section>
  </div>
  </section> 
  </div>

  <script src="js\script.js"></script>   
</body>
{% endblock body %}
</html>


   

accounts/templates/accounts/register.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="icon" href="favicon.ico">
  <title>Register | CRYSTALEVENT</title>
</head>
<body>
  
</body>
</html>

accounts/templates/accounts/reset-password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'accounts\css\reset.password.css' %}" />
    <link rel="stylesheet" href="{% static 'accounts\css\bootstrap.min.css' %}" />
    <title>Reset Password | CRYSTALEVENT</title>
</head>
{% block body %}
<body>
    
    <div class="header-postion w-100 ">
        <div class="d-flex justify-content-between align-content-center w-100">
          <div class="back-button">
            
            <a href="">
         <button type="submit" class="btn btn-primary border-0 ms-3">Back</button>
            </a>
        </div>
         <!-- <div class="container-fluid"> -->
           <!-- <div class=" d-flex  align-items-end justify-content-end"> -->
             <a href="{% url 'home:index' %}" class="navbar-brand ms-auto">
               <img
                 src="{% static 'accounts\img\landing-page img\site-logo.png' %}"
                 width="20"
                 height="20"
                 class="img-fluid"
                 alt="logo"
               />
               <span class="site-logo text-dark">CRYSTALEVENT</span>
             </a>
           <!-- </div> -->
          </div> 
       </div>
       </div>
   <!-- <div class="big-screen"> -->
    <div class="Reset-password">
     <div class="container-mobile">
       <section class="d-flex">
         <section class="Image">
         </section>
        
         <section class="  mt-5 ps-md-3 px-lg-5">
            <div class="container">  
                   
               <h2 class="text-center mt-5 text-log container-md font-playfair" > <span class="ms-2">Reset </span> <span class="orange">Password</span></h2>
               <p class="mt-5 reset-text fw-bold font-source"> 
                
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                <strong> Message:</strong> {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="close">
                <span aria-hidden="true">&times;</span>
                </button>
                </div>
                {% endfor %}
                
                Enter the email associated with your account and 
                we’ll send an email with 
                instructions to reset your password.</p>
               
               <form method="post">
                  {% csrf_token %}
                 <div class="mb-5">
                   <label for="exampleInputEmail1" class="form-label fw-bolder fs-5 label-size font-playfair">Email</label>
                   <input type="email" class="form-control font-source" placeholder="mariamevents247@gmail.com" name="email"   id="exampleInputEmail1" aria-describedby="emailHelp">
                   </div>
                
                 <div class=" d-flex justify-content-center mt-4 mb-4">
                 <button type="submit" class="btn btn-primary w-75 border-0 font-source fw-bold">Reset Password</button>
                 </div>
               </form>
         </div>
         
         </section>
       </div>
       </section> 
       </div>  
     </body>
   </html>
{% endblock body %}
    
</body>
</html>

accounts/templates/accounts/signout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'home/css/login.css' %}" />
    <link rel="stylesheet" href="{% static 'home/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <title>Login | CRYSTALEVENT</title>
  </head>
  <body class="position-relative">

    <div class="header-postion w-100 ">
     <div class="d-flex justify-content-between align-content-center w-100">
      <div class="back-button">
        <a href="index.html">
      <button type="submit" class="btn btn-primary border-0 ms-3">Back</button>
        </a>
    </div>
      <!-- <div class="container-fluid"> -->
        <!-- <div class=" d-flex  align-items-end justify-content-end"> -->
          <a href="index.html" class="navbar-brand ms-auto">
            <img
              src="{% static 'home/img/landing-page img/site-logo.png' %}"
              width="20"
              height="20"
              class="img-fluid"
              alt="logo"
            />
            <span class="site-logo text-dark">CRYSTALEVENT</span>
          </a>
        <!-- </div> -->
       </div> 
    </div>
    </div>
<!-- <div class="big-screen"> -->
  <div class="container-mobile">
    <section class="d-flex">
      
      <section class="Image">
      </section>
      
      <section class="form   mt-5 ps-md-3 px-lg-5 mt-5">
        <div class="container container-md">
                  
            <h2 class="text-center mt-5 text-log font-playfair" > <span class="ms-2">Log </span> <span class="orange">In</span></h2>

            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            <strong> Message:</strong> {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="close">
            <span aria-hidden="true">&times;</span>
            </button>
            </div>
            {% endfor %}

            You have successfully Logout, Click the link below To Login again
          <a href="{% url 'accounts:login' %}">Login</a>
                  
        
        </div>
      
      </section>
    </div>
    </section> 
    </div> 
    <script src="{% static 'home/js/script.js' %}"></script> 
  </body>
</html>

accounts/templates/accounts/verify.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'accounts\./css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'accounts\./css/verify.css' %}">
  <link rel="icon" href="favicon.ico">
  <title>Verify | CRYSTALEVENT</title>
</head>
<body>
  <section class="mb-2 position-relative">
    <nav class="navbar tab  navbar-expand-lg navbar-light position-absolute ms-2 mt-3" style="z-index: 1;">
      <button type="button" class="btn back ms-2"><a href="#" style="color: #fff;">Back</a></button>
        <a href="{% url 'home:index' %}" class="navbar-brand marginStyle">
            <img
            src="{% static 'accounts\./img/landing-page img/site-logo.png' %}"
            width="20"
            height="20"
            class="img-fluid"
            alt="logo"
            />
            <span class="site-logo" style="color: #522B05;">CRYSTALEVENT</span>
        </a>
    </nav>
      <div class="d-flex form-div justify-content-between" style="gap: 1px;">
          <div class="image position-relative">
              <div class="wineImg"></div>
              <div class="position-absolute top-50 form-texts">
                  <h3 class="text-white mt-3 text-center fs-1">Register to be among  our team</h3>
              </div>
          </div>
          <div class="form-body">
            
            <h3 class="text-center pt-5 mb-5 fw-bold">Verify your details</h3>

              <form method="post" class="">
                {% csrf_token %}
                <div class="my-5">
                  <h5 class="fw-bold">Your Name</h5>
                  <p class="fs-5">{{ verified.name }}</p>
                </div>

                <div class="my-5">
                  <h5 class="fw-bold">Email</h5>
                  <p class="fs-5">{{ verified.email }}</p>
                </div>

                <div class="my-5">
                  <h5 class="fw-bold">Phone Number</h5>
                  <p class="fs-5">{{ verified.phone }}</p>
                </div>

                <div class="my-5">
                  <h5 class="fw-bold">Select categories</h5>
                  <p class="fs-5">{{ verified.categories }}</p>
                </div>

                <div class="my-5">
                  <h5 class="fw-bold">Address</h5>
                  <p class="fs-5">{{ verified.address }}</p>
                </div>

                <div class="my-5">
                  <h5 class="fw-bold">State of residence</h5>
                  <p class="fs-5">{{ verified.statec }}</p>
                </div>

                <div class="my-5">
                  <h5 class="fw-bold">LGA</h5>
                  <p class="fs-5">{{ verified.lga }}</p>
                </div>

                <div>
                  <h5 for="experience" class="fw-bold">Experience</h5>
                  <p class="fs-5"> {{ verified.experience }}</p>
                </div>
                <input type="hidden" name ="ID" value="{{verified.id}}" required></td></tr>

                <div class="d-grid gap-2 bg-hire text-white rounded" style="margin-top: 50px;">
                  <a href="{% url 'accounts:booking' %}"><button class="btn text-white" type="button"> Click to book an appointment</button></a>
                </div>
                <div class="d-grid gap-2 bg-hire text-white rounded">
                    
                </div>
                <div class="d-grid gap-2 bg-hire text-white rounded">
                
                </div>
              </form>
          </div>
      </div>
  </section>
</body>
</html>